### PR TITLE
Add NoOpTokenValidator for use in testing token authenticated endpoints

### PR DESCRIPTION
**Pull request by mrobinet**
I have a need for this in a new service and don't want to duplicate it from existing services.

### CODE REVIEW

**Comment by charliek** [comment]
Because this is in the test directory it will not be in the jar that is exported by the project. We'd have to add it to the main source or have a separate test jar to get you what it looks like you want. Maybe let's discuss the options tomorrow.

**Comment by mrobinet** [comment]
Ohh yeah, I should have realized that. I'm out until Monday, but can move it when I get back.

**Comment by mrobinet** [comment]
This should be ready for another look now.

**Comment by beckje01** [comment]
Seems ok for now eventually it should be a multi project build with the text helpers outside I think but for now this is fine.

**Pull request merged**
