### PR TITLE
Publish releases to bintray

### PR DESCRIPTION
**Pull request by charliek**
Tested the publishing, but removed version for now. Figure we can publish the next version as the first.

Also updated to gradle 2.7.

/cc @beckje01

### CODE REVIEW

**Comment by beckje01** [comment]
:+1:

**Comment by charliek** [comment]
Thinking about changing this to be "smartthings:ratpack-bearer-auth" before publishing.  "smartthings.ratpack" as the group seems redundant.  Then we can have future packages follow the same naming patterns.

**Comment by beckje01** [comment]
Agreed that's better

**Comment by beckje01** [comment]
Do you want to change the name on this and we will start publishing?

**Comment by charliek** [comment]
Forgot about this... I'll update this and get it merged tomorrow.

**Pull request merged**
